# Generated by Django 3.2.15 on 2022-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kouho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='氏名')),
                ('age', models.PositiveSmallIntegerField(verbose_name='年齢')),
                ('kao', models.ImageField(upload_to='', verbose_name='顔写真')),
                ('tou', models.CharField(max_length=20, verbose_name='所属政党')),
                ('career', models.TextField(verbose_name='経歴')),
                ('manifesto_class', models.CharField(max_length=20, verbose_name='選挙公約分類')),
                ('fl1', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ1')),
                ('fl2', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ2')),
                ('fl3', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ3')),
                ('fl4', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ4')),
                ('fl5', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ5')),
                ('fl6', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ6')),
                ('fl7', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ7')),
                ('fl8', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ8')),
                ('fl9', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ9')),
                ('fl10', models.CharField(default='unchecked', max_length=20, verbose_name='フラグ10')),
                ('manifesto', models.TextField(verbose_name='選挙公約')),
                ('instagram', models.URLField(verbose_name='instergram')),
                ('twitter', models.URLField(verbose_name='twitter')),
                ('facebook', models.URLField(verbose_name='facebook')),
            ],
        ),
        migrations.CreateModel(
            name='Seitou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seitou_name', models.CharField(max_length=20, verbose_name='政党名')),
                ('body', models.TextField(verbose_name='政党説明')),
            ],
        ),
    ]
