# Generated by Django 3.2.15 on 2022-10-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senkyo', '0002_auto_20221026_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_content',
            field=models.TextField(verbose_name='テキスト'),
        ),
    ]
