# Generated by Django 3.2.15 on 2022-11-16 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('senkyo', '0003_alter_chat_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
