# Generated by Django 3.2.15 on 2022-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senkyo', '0004_chat_posted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='ニックネーム')),
                ('mail', models.EmailField(max_length=120, verbose_name='メールアドレス')),
            ],
        ),
    ]
