# Generated by Django 3.2.15 on 2023-01-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senkyo', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kouho',
            name='kao',
            field=models.ImageField(upload_to='uploads/', verbose_name='顔写真'),
        ),
    ]
